name: Python CI

on:
  push:
    branches:
      - main   # Ana branch'ınıza göre düzenleyin
  pull_request:
    branches:
      - main   # Ana branch'ınıza göre düzenleyin

jobs:
  test:
    runs-on: ubuntu-latest  # CI işlemini çalıştırmak için kullanılan ortam

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Python sürümünü burada belirtin

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Gereksinimlerinizi yükler

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Testleri çalıştırır

      - name: Check for invalid characters
        run: |
          invalid_lines=$(pytest test_yazim_kontrol.py | grep "Geçersiz içerik bulundu")
          if [ ! -z "$invalid_lines" ]; then
            echo "Hata: Geçersiz içerik tespit edildi: $invalid_lines"
            exit 1  # Hata durumunda exit 1 ile işlemi başarısız yapar
          else
            echo "Testler başarılı!"
          fi
