name: Python Tests

on:
  push:
    branches:
      - main  # Ana dalda (main) yapılan push işlemleri tetiklenir
    paths:
      - "girdi.txt"  # Sadece girdi.txt dosyasındaki değişikliklerde tetiklenir
  pull_request:
    branches:
      - main  # Main branch'e pull request yapıldığında tetiklenir
    paths:
      - "girdi.txt"  # Yalnızca girdi.txt dosyasına yapılan değişiklikler
jobs:
  test:
    runs-on: ubuntu-latest  # GitHub Actions için Ubuntu ortamı

    steps:
    - name: Check out repository
      uses: actions/checkout@v2  # Repository'i al

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Python versiyonu belirleme
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Pip'i güncelle
        pip install -r requirements.txt  # Proje bağımlılıklarını yükle

    - name: Run the Python script
      run: |
        python main.py  # main.py dosyasını çalıştır

    - name: Commit the output (optional)
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-github-username"
        git add ciktilar.txt  # Çıktı dosyasını ekle
        git commit -m "Update ciktilar.txt with corrected text"
        git push origin main  # Güncellenmiş ciktilar.txt dosyasını tekrar GitHub'a gönder
