name: Python Tests

on:
  push:
    branches:
      - main  # Ana dal üzerinde yapılan push işlemleri tetiklesin
  pull_request:
    branches:
      - main  # Ana dala yapılan PR'lar tetiklesin

jobs:
  test:
    runs-on: ubuntu-latest  # Ubuntu üzerinde çalışacak

    steps:
      # 1. Python'ı kurma
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Python sürümünü belirtin, örneğin 3.9

      # 2. Bağımlılıkları yükleme
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Testleri çalıştırma
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Testleri çalıştır

      # 4. Hata olması durumunda bildirim
      - name: Upload Test Results (optional)
        if: failure()  # Test başarısız olursa çalışır
        run: |
          echo "Test failed. Check the logs for details."

