name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create girdi.txt file
        run: |
          echo "Merhaba, bu bir deneme metnidir." > girdi.txt

      - name: Run the Python program
        run: |
          python main.py

      - name: Configure Git for GitHub Actions
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update ciktilar.txt with corrected text"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/bnymnerd/yazim_kontrol.git

      - name: Check ciktilar.txt for invalid content
        run: |
          python check_invalid_content.py ciktilar.txt

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ciktilar.txt
