name: CI Workflow

on:
  push:
    branches:
      - main  # main branch'ine yapılan push'larda tetiklenecek
  pull_request:
    branches:
      - main  # main branch'ine yapılan pull request'lerde tetiklenecek

jobs:
  test:
    runs-on: ubuntu-latest  # GitHub Actions çalıştırma ortamı (Ubuntu kullanıyoruz)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Kodu çekiyoruz

      - name: Set up Python
        uses: actions/setup-python@v2  # Python ortamını kuruyoruz
        with:
          python-version: '3.8'  # Python sürümü

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Gerekli kütüphaneleri yüklüyoruz

      - name: Create girdi.txt file
        run: |
          echo "Merhaba, bu bir deneme metnidir." > girdi.txt  # girdi.txt dosyasını oluşturuyoruz

      - name: Run the Python program
        run: |
          python main.py  # Python programını çalıştırıyoruz

      - name: Check ciktilar.txt for invalid content
        run: |
          python -c '
import re

def check_invalid_content(file_path):
    invalid_pattern = re.compile(r"[0-9!@#$%^&*(),.?\":{}|<>]")
    with open(file_path, "r") as file:
        lines = file.readlines()
    invalid_lines = []
    for i, line in enumerate(lines):
        if invalid_pattern.search(line):
            invalid_lines.append((i + 1, line.strip()))
    if invalid_lines:
        raise Exception(f"Geçersiz içerik bulundu: {invalid_lines}")
          
check_invalid_content("ciktilar.txt")'  # ciktilar.txt dosyasını kontrol ediyoruz

      - name: Upload test results
        if: failure()  # Test başarısız olursa sonuçları yükle
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ciktilar.txt
